/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BecomeHostRouteImport } from './routes/become-host'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HSlugRouteImport } from './routes/h.$slug'
import { Route as EEventIdRouteImport } from './routes/e.$eventId'
import { Route as DashboardHostIdRouteImport } from './routes/dashboard.$hostId'
import { Route as DashboardHostIdIndexRouteImport } from './routes/dashboard.$hostId.index'
import { Route as DashboardHostIdReportsRouteImport } from './routes/dashboard.$hostId.reports'
import { Route as DashboardHostIdMembersRouteImport } from './routes/dashboard.$hostId.members'
import { Route as ApiPublicSeedDemoRouteImport } from './routes/api/public/seed-demo'
import { Route as DashboardHostIdEventsEventIdRouteImport } from './routes/dashboard.$hostId.events.$eventId'
import { Route as ApiPublicSitemapXmlRouteImport } from './routes/api/public/sitemap.xml'
import { Route as ApiPublicRobotsTxtRouteImport } from './routes/api/public/robots.txt'
import { Route as DashboardHostIdEventsEventIdIndexRouteImport } from './routes/dashboard.$hostId.events.$eventId.index'
import { Route as DashboardHostIdEventsEventIdAttendeesRouteImport } from './routes/dashboard.$hostId.events.$eventId.attendees'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeHostRoute = BecomeHostRouteImport.update({
  id: '/become-host',
  path: '/become-host',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HSlugRoute = HSlugRouteImport.update({
  id: '/h/$slug',
  path: '/h/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EEventIdRoute = EEventIdRouteImport.update({
  id: '/e/$eventId',
  path: '/e/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHostIdRoute = DashboardHostIdRouteImport.update({
  id: '/dashboard/$hostId',
  path: '/dashboard/$hostId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHostIdIndexRoute = DashboardHostIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardHostIdRoute,
} as any)
const DashboardHostIdReportsRoute = DashboardHostIdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardHostIdRoute,
} as any)
const DashboardHostIdMembersRoute = DashboardHostIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardHostIdRoute,
} as any)
const ApiPublicSeedDemoRoute = ApiPublicSeedDemoRouteImport.update({
  id: '/api/public/seed-demo',
  path: '/api/public/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHostIdEventsEventIdRoute =
  DashboardHostIdEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => DashboardHostIdRoute,
  } as any)
const ApiPublicSitemapXmlRoute = ApiPublicSitemapXmlRouteImport.update({
  id: '/api/public/sitemap/xml',
  path: '/api/public/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobotsTxtRoute = ApiPublicRobotsTxtRouteImport.update({
  id: '/api/public/robots/txt',
  path: '/api/public/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHostIdEventsEventIdIndexRoute =
  DashboardHostIdEventsEventIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardHostIdEventsEventIdRoute,
  } as any)
const DashboardHostIdEventsEventIdAttendeesRoute =
  DashboardHostIdEventsEventIdAttendeesRouteImport.update({
    id: '/attendees',
    path: '/attendees',
    getParentRoute: () => DashboardHostIdEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/become-host': typeof BecomeHostRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tickets': typeof TicketsRoute
  '/dashboard/$hostId': typeof DashboardHostIdRouteWithChildren
  '/e/$eventId': typeof EEventIdRoute
  '/h/$slug': typeof HSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/dashboard/$hostId/members': typeof DashboardHostIdMembersRoute
  '/dashboard/$hostId/reports': typeof DashboardHostIdReportsRoute
  '/dashboard/$hostId/': typeof DashboardHostIdIndexRoute
  '/api/public/robots/txt': typeof ApiPublicRobotsTxtRoute
  '/api/public/sitemap/xml': typeof ApiPublicSitemapXmlRoute
  '/dashboard/$hostId/events/$eventId': typeof DashboardHostIdEventsEventIdRouteWithChildren
  '/dashboard/$hostId/events/$eventId/attendees': typeof DashboardHostIdEventsEventIdAttendeesRoute
  '/dashboard/$hostId/events/$eventId/': typeof DashboardHostIdEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/become-host': typeof BecomeHostRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tickets': typeof TicketsRoute
  '/e/$eventId': typeof EEventIdRoute
  '/h/$slug': typeof HSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/dashboard/$hostId/members': typeof DashboardHostIdMembersRoute
  '/dashboard/$hostId/reports': typeof DashboardHostIdReportsRoute
  '/dashboard/$hostId': typeof DashboardHostIdIndexRoute
  '/api/public/robots/txt': typeof ApiPublicRobotsTxtRoute
  '/api/public/sitemap/xml': typeof ApiPublicSitemapXmlRoute
  '/dashboard/$hostId/events/$eventId/attendees': typeof DashboardHostIdEventsEventIdAttendeesRoute
  '/dashboard/$hostId/events/$eventId': typeof DashboardHostIdEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/become-host': typeof BecomeHostRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tickets': typeof TicketsRoute
  '/dashboard/$hostId': typeof DashboardHostIdRouteWithChildren
  '/e/$eventId': typeof EEventIdRoute
  '/h/$slug': typeof HSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/dashboard/$hostId/members': typeof DashboardHostIdMembersRoute
  '/dashboard/$hostId/reports': typeof DashboardHostIdReportsRoute
  '/dashboard/$hostId/': typeof DashboardHostIdIndexRoute
  '/api/public/robots/txt': typeof ApiPublicRobotsTxtRoute
  '/api/public/sitemap/xml': typeof ApiPublicSitemapXmlRoute
  '/dashboard/$hostId/events/$eventId': typeof DashboardHostIdEventsEventIdRouteWithChildren
  '/dashboard/$hostId/events/$eventId/attendees': typeof DashboardHostIdEventsEventIdAttendeesRoute
  '/dashboard/$hostId/events/$eventId/': typeof DashboardHostIdEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/become-host'
    | '/explore'
    | '/my-events'
    | '/sign-in'
    | '/sign-up'
    | '/tickets'
    | '/dashboard/$hostId'
    | '/e/$eventId'
    | '/h/$slug'
    | '/invite/$token'
    | '/dashboard/'
    | '/api/public/seed-demo'
    | '/dashboard/$hostId/members'
    | '/dashboard/$hostId/reports'
    | '/dashboard/$hostId/'
    | '/api/public/robots/txt'
    | '/api/public/sitemap/xml'
    | '/dashboard/$hostId/events/$eventId'
    | '/dashboard/$hostId/events/$eventId/attendees'
    | '/dashboard/$hostId/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/become-host'
    | '/explore'
    | '/my-events'
    | '/sign-in'
    | '/sign-up'
    | '/tickets'
    | '/e/$eventId'
    | '/h/$slug'
    | '/invite/$token'
    | '/dashboard'
    | '/api/public/seed-demo'
    | '/dashboard/$hostId/members'
    | '/dashboard/$hostId/reports'
    | '/dashboard/$hostId'
    | '/api/public/robots/txt'
    | '/api/public/sitemap/xml'
    | '/dashboard/$hostId/events/$eventId/attendees'
    | '/dashboard/$hostId/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/become-host'
    | '/explore'
    | '/my-events'
    | '/sign-in'
    | '/sign-up'
    | '/tickets'
    | '/dashboard/$hostId'
    | '/e/$eventId'
    | '/h/$slug'
    | '/invite/$token'
    | '/dashboard/'
    | '/api/public/seed-demo'
    | '/dashboard/$hostId/members'
    | '/dashboard/$hostId/reports'
    | '/dashboard/$hostId/'
    | '/api/public/robots/txt'
    | '/api/public/sitemap/xml'
    | '/dashboard/$hostId/events/$eventId'
    | '/dashboard/$hostId/events/$eventId/attendees'
    | '/dashboard/$hostId/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BecomeHostRoute: typeof BecomeHostRoute
  ExploreRoute: typeof ExploreRoute
  MyEventsRoute: typeof MyEventsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TicketsRoute: typeof TicketsRoute
  DashboardHostIdRoute: typeof DashboardHostIdRouteWithChildren
  EEventIdRoute: typeof EEventIdRoute
  HSlugRoute: typeof HSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiPublicSeedDemoRoute: typeof ApiPublicSeedDemoRoute
  ApiPublicRobotsTxtRoute: typeof ApiPublicRobotsTxtRoute
  ApiPublicSitemapXmlRoute: typeof ApiPublicSitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-host': {
      id: '/become-host'
      path: '/become-host'
      fullPath: '/become-host'
      preLoaderRoute: typeof BecomeHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$slug': {
      id: '/h/$slug'
      path: '/h/$slug'
      fullPath: '/h/$slug'
      preLoaderRoute: typeof HSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$eventId': {
      id: '/e/$eventId'
      path: '/e/$eventId'
      fullPath: '/e/$eventId'
      preLoaderRoute: typeof EEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$hostId': {
      id: '/dashboard/$hostId'
      path: '/dashboard/$hostId'
      fullPath: '/dashboard/$hostId'
      preLoaderRoute: typeof DashboardHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$hostId/': {
      id: '/dashboard/$hostId/'
      path: '/'
      fullPath: '/dashboard/$hostId/'
      preLoaderRoute: typeof DashboardHostIdIndexRouteImport
      parentRoute: typeof DashboardHostIdRoute
    }
    '/dashboard/$hostId/reports': {
      id: '/dashboard/$hostId/reports'
      path: '/reports'
      fullPath: '/dashboard/$hostId/reports'
      preLoaderRoute: typeof DashboardHostIdReportsRouteImport
      parentRoute: typeof DashboardHostIdRoute
    }
    '/dashboard/$hostId/members': {
      id: '/dashboard/$hostId/members'
      path: '/members'
      fullPath: '/dashboard/$hostId/members'
      preLoaderRoute: typeof DashboardHostIdMembersRouteImport
      parentRoute: typeof DashboardHostIdRoute
    }
    '/api/public/seed-demo': {
      id: '/api/public/seed-demo'
      path: '/api/public/seed-demo'
      fullPath: '/api/public/seed-demo'
      preLoaderRoute: typeof ApiPublicSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$hostId/events/$eventId': {
      id: '/dashboard/$hostId/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/dashboard/$hostId/events/$eventId'
      preLoaderRoute: typeof DashboardHostIdEventsEventIdRouteImport
      parentRoute: typeof DashboardHostIdRoute
    }
    '/api/public/sitemap/xml': {
      id: '/api/public/sitemap/xml'
      path: '/api/public/sitemap/xml'
      fullPath: '/api/public/sitemap/xml'
      preLoaderRoute: typeof ApiPublicSitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robots/txt': {
      id: '/api/public/robots/txt'
      path: '/api/public/robots/txt'
      fullPath: '/api/public/robots/txt'
      preLoaderRoute: typeof ApiPublicRobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$hostId/events/$eventId/': {
      id: '/dashboard/$hostId/events/$eventId/'
      path: '/'
      fullPath: '/dashboard/$hostId/events/$eventId/'
      preLoaderRoute: typeof DashboardHostIdEventsEventIdIndexRouteImport
      parentRoute: typeof DashboardHostIdEventsEventIdRoute
    }
    '/dashboard/$hostId/events/$eventId/attendees': {
      id: '/dashboard/$hostId/events/$eventId/attendees'
      path: '/attendees'
      fullPath: '/dashboard/$hostId/events/$eventId/attendees'
      preLoaderRoute: typeof DashboardHostIdEventsEventIdAttendeesRouteImport
      parentRoute: typeof DashboardHostIdEventsEventIdRoute
    }
  }
}

interface DashboardHostIdEventsEventIdRouteChildren {
  DashboardHostIdEventsEventIdAttendeesRoute: typeof DashboardHostIdEventsEventIdAttendeesRoute
  DashboardHostIdEventsEventIdIndexRoute: typeof DashboardHostIdEventsEventIdIndexRoute
}

const DashboardHostIdEventsEventIdRouteChildren: DashboardHostIdEventsEventIdRouteChildren =
  {
    DashboardHostIdEventsEventIdAttendeesRoute:
      DashboardHostIdEventsEventIdAttendeesRoute,
    DashboardHostIdEventsEventIdIndexRoute:
      DashboardHostIdEventsEventIdIndexRoute,
  }

const DashboardHostIdEventsEventIdRouteWithChildren =
  DashboardHostIdEventsEventIdRoute._addFileChildren(
    DashboardHostIdEventsEventIdRouteChildren,
  )

interface DashboardHostIdRouteChildren {
  DashboardHostIdMembersRoute: typeof DashboardHostIdMembersRoute
  DashboardHostIdReportsRoute: typeof DashboardHostIdReportsRoute
  DashboardHostIdIndexRoute: typeof DashboardHostIdIndexRoute
  DashboardHostIdEventsEventIdRoute: typeof DashboardHostIdEventsEventIdRouteWithChildren
}

const DashboardHostIdRouteChildren: DashboardHostIdRouteChildren = {
  DashboardHostIdMembersRoute: DashboardHostIdMembersRoute,
  DashboardHostIdReportsRoute: DashboardHostIdReportsRoute,
  DashboardHostIdIndexRoute: DashboardHostIdIndexRoute,
  DashboardHostIdEventsEventIdRoute:
    DashboardHostIdEventsEventIdRouteWithChildren,
}

const DashboardHostIdRouteWithChildren = DashboardHostIdRoute._addFileChildren(
  DashboardHostIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BecomeHostRoute: BecomeHostRoute,
  ExploreRoute: ExploreRoute,
  MyEventsRoute: MyEventsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TicketsRoute: TicketsRoute,
  DashboardHostIdRoute: DashboardHostIdRouteWithChildren,
  EEventIdRoute: EEventIdRoute,
  HSlugRoute: HSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiPublicSeedDemoRoute: ApiPublicSeedDemoRoute,
  ApiPublicRobotsTxtRoute: ApiPublicRobotsTxtRoute,
  ApiPublicSitemapXmlRoute: ApiPublicSitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
